import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { CssBaseline, ThemeProvider } from "@mui/material";
import theme from "./theme";
import Auth from "./auth/auth";
import QueryProvider from "./utils/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Soil Moisture Monitor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <CssBaseline />
          <AppRouterCacheProvider>
            <Auth>
              <ThemeProvider theme={theme}>{children}</ThemeProvider>
            </Auth>
          </AppRouterCacheProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
